main: me.sowgro.LeaveCmd.Main
name: LeaveCmd
author: sowgro
version: 1.0
api-version: 1.16

commands:
  leave:
    description: Leave the current game
    permission: leaveCmd.leave
  leaveCmd:
    permission: leaveCmd.admin

permissions:
  leaveCmd.leave:
    default: true
  leaveCmd.reload:
    default: op